---
services:
  rabbitmq:
    image: "docker.io/rabbitmq:3.13.1-management"
    restart: "always"
    environment:
      RABBITMQ_DEFAULT_USER: "testuser"
      RABBITMQ_DEFAULT_PASS: "testpass"
    ports:
      - "5672:5672"
      - "15672:15672"

  vault:
    image: hashicorp/vault:1.16.2
    restart: always
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "test"
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"
